version: "3.4"

services:
  application:
    build: .
    restart: always
    container_name: spring_application
    depends_on:
      - postgres
    ports:
      - "8081:8081"
  postgres:
    image: postgres:12.2-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: security_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonar" ]
      interval: 10s
      timeout: 5s
      retries: 5